repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        types: [html]
      - id: end-of-file-fixer
        types: [html]
      - id: check-merge-conflict
        types: [html]

  - repo: local
    hooks:
      - id: htmlhint
        name: htmlhint
        entry: npx htmlhint
        language: system
        types: [html]
